### ISSUE TITLE
Multiple elements missing from NTMAIi 

### ISSUE THREAD

**Issue by Graham1225** [LocalInsomniac/NTMAi#9]
After watching a couple of videos on it, I was really excited to download the mod. However, multiple elements are not present when I load the game: voxels are missing, secondary fires just... don't work at all, music is missing in places, Doom Guy barely says anything, and the grenade button only works half the time.
I am running on a 2020 M1 Macbook Air with the most recent release of GZDoom. 
Everything else is great though. The movement is perfect and its basically a perfect blend of DK3D and Blood with a Doom aesthetic.

**Comment by localins** [comment]
Those videos are reviewing an ancient version of NTMAi and are no longer representative of this mod.
- Voxels were omitted due to GZDoom having technical difficulties with them.
- Altfires were removed because most of them were too situational and too few to begin with.
- NTMAi doesn't replace any music tracks at all (unless you're playing MAYhem 2019)
- Doomguy has his vanilla voice lines again, because old NTMAi's were simply Not Good™
- The grenade button doesn't work because you don't have any grenades in your inventory. Good call, though. I should add an indicator for that.

If you want to play NTMAi like how it was during the Renaissance, you can find it from Releases marked under "pre-release": https://github.com/LocalInsomniac/NTMAi/releases/tag/0.4.9
